api:
  listen: ":8000"
  cors_origins: "http://127.0.0.1,http://localhost,http://127.0.0.1:80,http://localhost:80"

admin:
  listen: ":9092"

auth:
  enabled: false
  google_client_id_env: "GOOGLE_CLIENT_ID"
  google_client_id: ""

database:
  url_env: "DATABASE_URL"
  max_conns: 10
  min_conns: 1
  max_lifetime: 1h

online_threshold: 5m
