# Build
FROM golang:1.25-bookworm@sha256:ea341baa9bd5ba6784f6d7161ace70544349a6242d54d34a0fbfd2c4d51c9d58 AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /out/api ./cmd/api

# Runtime
FROM gcr.io/distroless/static-debian12:nonroot@sha256:f5b485ea962d9bd1186b2f6b3a061191539b905b82ec395de78cbfae51f20e35
WORKDIR /
COPY --from=build /out/api /api
COPY configs/api.example.yaml /configs/api.example.yaml
USER nonroot:nonroot
EXPOSE 8000 9092
ENTRYPOINT ["/api"]
CMD ["-config", "/configs/api.example.yaml"]
